# .github/workflows/release.yml
name: Release Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools twine
          
      - name: Create package files
        run: |
          # Create pyproject.toml
          cat > pyproject.toml << EOL
          [build-system]
          requires = ["setuptools>=61.0"]
          build-backend = "setuptools.build_meta"

          [project]
          name = "acestream-scraper"
          version = "\${VERSION}"
          description = "Acestream channel scraper with ZeroNet support"
          readme = "README.md"
          authors = [{name = "pipepito"}]
          license = {text = "MIT"}
          classifiers = [
              "Programming Language :: Python :: 3",
              "License :: OSI Approved :: MIT License",
              "Operating System :: OS Independent",
          ]
          dependencies = [
              "aiohttp>=3.11.12",
              "asgiref>=3.4.1",
              "beautifulsoup4>=4.9.3",
              "flask[async]>=2.0.1",
              "flask-migrate>=4.0.5",
              "flask-sqlalchemy>=2.5.1",
              "sqlalchemy>=1.4.23",
              "werkzeug>=2.0.3",
          ]

          [project.urls]
          Homepage = "https://github.com/yourusername/acestream-scraper"
          EOL

          # Update version in pyproject.toml
          VERSION=${GITHUB_REF_NAME#v}
          sed -i "s/\${VERSION}/$VERSION/" pyproject.toml
          
          # Create __init__.py with version
          echo "__version__ = '$VERSION'" > app/__init__.py
          
      - name: Build package
        run: python -m build
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          draft: false
          prerelease: false
          generate_release_notes: true
